apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ansibleee-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AnsibleEE is the Schema for the ansibleees API
      displayName: Ansible EE
      kind: AnsibleEE
      name: ansibleees.redhat.com
      version: v1alpha1
  description: The Ansible Execution Environment Operator
  displayName: AnsibleEE
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ansible
  - execution
  links:
  - name: Ansibleee Operator
    url: https://ansibleee-operator.domain
  maintainers:
  - email: jlarriba@redhat.com
    name: Juan Larriba
  maturity: alpha
  provider:
    name: jlarriba
  version: 0.0.0
