apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-plugin
  namespace: openstack
spec:
  playbook: test.yaml
  image: quay.io/adrbrown/osp-ansible-runner:latest
  inventory: /runner/inventory
  env:
    - name: RUNNER_PLUGIN
      value: |
        export OS_CLOUD=devstack-admin
  extraMounts:
    - volumes:
      - name: openstack
        configMap:
          name: openstack-configmap
      - name: clouds
        configMap:
          name: clouds-configmap
      mounts:
      - name: openstack
        mountPath: /runner/inventory/plugin/openstack.yaml
        subPath: openstack.yaml
      - name: clouds
        mountPath: /runner/inventory/plugin/clouds.yaml
        subPath: clouds.yaml
