apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-plugin
  namespace: openstack
spec:
  # args: ["ansible-inventory", "-i", "/inventory/inventory.yaml", "--list"]
  # play: |
  #   - name: ping static inventory
  #     hosts: all
  #     tasks:
  #     - name: Testing ping
  #       ansible.builtin.ping:
  image: quay.io/adrbrown/osp-ansible-runner:dev-plugin-revert
  inventory: |
    plugin: edpm_plugin                   
    path_to_inventory: /runner/inventory   
    inventory_file: edpm_inventory.yaml 
  env:
    - name: RUNNER_PLUGIN
      value: ANSIBLE_INVENTORY_PLUGINS=/runner/plugin