apiVersion: redhat.com/v1alpha1
kind: AnsibleEE
metadata:
  name: ansibleee-plugin
  namespace: openstack
spec:
  playbook: deploy-tripleo-os-configure.yml
  image: quay.io/adrbrown/osp-ansible-runner:latest
  inventory: |
    Compute:
      hosts:
        compute-0:
          ansible_host: 10.0.0.4
      vars:
        ansible_ssh_user: root
    allovercloud:
      children:
        Compute:
    overcloud:
      children:
        Compute:
  env:
    - name: RUNNER_PLUGIN
      value: |
        ansible-playbook -i inventory/plugin/edpm_plugin.py --list-hosts $RUNNER_INVENTORY

